### ISSUE TITLE
Membangun untuk GNU Aspell

### ISSUE THREAD

**Issue by azzamsa** [idnux/thes-id#2]
Saya juga ada rencana untuk membangun kamus dengan padanan bahasa Indonesia terbaru untuk GNU Aspell.

Pranala ini http://arsip.blankonlinux.or.id/blankon/pool/main/s/stardict-tbipb1/stardict-tbipb1_2.4.2-0blankon6.tar.gz sudah rusak.

Sementara saya ingin mengkompilasinya dari [Indonesian Word List](https://github.com/geovedi/indonesian-wordlist).

Apakah Bapak ada rekomendasi untuk sumber daftar kata bahasa Indonesia ?

**Comment by azzamsa** [comment]
saya coba ambil dari http://arsip.blankonlinux.or.id/blankon/pool/main/s/stardict-tbipb1/stardict-tbipb1_2.4.2-0blankon6_all.deb, tetapi data nya sudah berupa binary.

**Comment by layangankertas** [comment]
coba ambil dari http://arsip.blankonlinux.or.id/blankon/pool/main/s/stardict-tbipb1/stardict-tbipb1_2.4.2-0blankon6_all.deb saja mas. sebenarnya antara paket kode sumber sama paket biner isinya sama saja. nanti anda bisa convert kamus stardictnya ke txt pakai perkakas stardict2txt yang terdapat di dalam paket stardict-tools.

silahkan dicoba

**Comment by layangankertas** [comment]
untuk sumber daftar kata mas azzamsa bisa menggunakan KBBI atau Kamus Tesaurus versi cetak

**Comment by azzamsa** [comment]
Untuk daftar kata, mas Idnux crawl dari KBBI online atau bagaimana ?

**Comment by layangankertas** [comment]
saya ambil dari kamus TPIPB stardict
