### ISSUE TITLE
wishlist: merge Indonesian thesaurus into LibreOffice

### ISSUE THREAD

**Issue by atriwidada** [idnux/thes-id#3]
Thesaurus can be included into LibreOffice not only as extension, but more tightly like dictionary. I would like to be involved in this integration if you are interested.

I have submitted a patch to include Indonesian dictionary into LibreOffice. It has accepted into master https://gerrit.libreoffice.org/#/c/49785/. I would like for us to create another patch to include Indonesian thesaurus, merged into Indonesian dictionary.

**Comment by atriwidada** [comment]
Patch to LibreOffice master created and uploaded to gerrit for review https://gerrit.libreoffice.org/#/c/50962/

Seems that there are many invalid entries in thes_id.txt

**Comment by atriwidada** [comment]
merged into libreoffice master https://gerrit.libreoffice.org/#/c/50962/

**Comment by layangankertas** [comment]
maaf, saya baru buka github ini, saya sangat senang jika kamus ini mau dimasukkan ke master kamus libreoffice.
cuma kalau boleh tau masalahnya ada di mana ya pak?
terima kasih

**Comment by atriwidada** [comment]
sudah beres kok, sebelumnya bermasalah (review di gerrit ditolak) karena ada 150+ entri yang bermasalah karena tidak ada line count, angka di line count salah, atau kurang newline. perbaikan masalah ini telah saya kirim lewat pull request ke repo ini, dan review di gerrit sudah diubah dari ditolak menjadi diterima.

**Comment by layangankertas** [comment]
iya pak, terima kasih atas bantuannya
maaf memang saya tidak sempat memeriksa satu persatu isi kamus tersebut dan saya juga tidak punya alat yang dapat memeriksanya secara tepat dan cepat
sekali lagi terima kasih banyak
